<?php

use App\Models\Catalogo\Paises;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class PaisesSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
        Model::unguard();
        DB::table('catalogo_pais')->truncate();

		Paises::create(['country_code' => 'AD', 'country_name' => 'Andorra','id_moneda'=>1]);
		Paises::create(['country_code' => 'AE', 'country_name' => 'United Arab Emirates','id_moneda'=>2]);
		Paises::create(['country_code' => 'AF', 'country_name' => 'Afghanistan','id_moneda'=>3]);
		Paises::create(['country_code' => 'AG', 'country_name' => 'Antigua and Barbuda','id_moneda'=>4]);
		Paises::create(['country_code' => 'AI', 'country_name' => 'Anguilla','id_moneda'=>5]);
		Paises::create(['country_code' => 'AL', 'country_name' => 'Albania','id_moneda'=>6]);
		Paises::create(['country_code' => 'AM', 'country_name' => 'Armenia','id_moneda'=>7]);
		Paises::create(['country_code' => 'AN', 'country_name' => 'Netherlands Antilles','id_moneda'=>1]);
		Paises::create(['country_code' => 'AO', 'country_name' => 'Angola','id_moneda'=>8]);
		Paises::create(['country_code' => 'AQ', 'country_name' => 'Antarctica','id_moneda'=>9]);
		Paises::create(['country_code' => 'AR', 'country_name' => 'Argentina','id_moneda'=>10]);
		Paises::create(['country_code' => 'AS', 'country_name' => 'American Samoa','id_moneda'=>11]);
		Paises::create(['country_code' => 'AT', 'country_name' => 'Austria','id_moneda'=>12]);
		Paises::create(['country_code' => 'AU', 'country_name' => 'Australia','id_moneda'=>13]);
		Paises::create(['country_code' => 'AW', 'country_name' => 'Aruba','id_moneda'=>14]);
		Paises::create(['country_code' => 'AX', 'country_name' => 'Aland Islands','id_moneda'=>15]);
		Paises::create(['country_code' => 'AZ', 'country_name' => 'Azerbaijan','id_moneda'=>16]);
		Paises::create(['country_code' => 'BA', 'country_name' => 'Bosnia and Herzegovina','id_moneda'=>17]);
		Paises::create(['country_code' => 'BB', 'country_name' => 'Barbados','id_moneda'=>18]);
		Paises::create(['country_code' => 'BD', 'country_name' => 'Bangladesh','id_moneda'=>19]);
		Paises::create(['country_code' => 'BE', 'country_name' => 'Belgium','id_moneda'=>20]);
		Paises::create(['country_code' => 'BF', 'country_name' => 'Burkina Faso','id_moneda'=>21]);
		Paises::create(['country_code' => 'BG', 'country_name' => 'Bulgaria','id_moneda'=>22]);
		Paises::create(['country_code' => 'BH', 'country_name' => 'Bahrain','id_moneda'=>23]);
		Paises::create(['country_code' => 'BI', 'country_name' => 'Burundi','id_moneda'=>24]);
		Paises::create(['country_code' => 'BJ', 'country_name' => 'Benin','id_moneda'=>25]);
		Paises::create(['country_code' => 'BL', 'country_name' => 'Saint Barthélemy','id_moneda'=>26]);
		Paises::create(['country_code' => 'BM', 'country_name' => 'Bermuda','id_moneda'=>27]);
		Paises::create(['country_code' => 'BN', 'country_name' => 'Brunei','id_moneda'=>28]);
		Paises::create(['country_code' => 'BO', 'country_name' => 'Bolivia','id_moneda'=>29]);
		Paises::create(['country_code' => 'BQ', 'country_name' => 'Bonaire, Saint Eustatius and Saba ','id_moneda'=>30]);
		Paises::create(['country_code' => 'BR', 'country_name' => 'Brazil','id_moneda'=>31]);
		Paises::create(['country_code' => 'BS', 'country_name' => 'Bahamas','id_moneda'=>32]);
		Paises::create(['country_code' => 'BT', 'country_name' => 'Bhutan','id_moneda'=>33]);
		Paises::create(['country_code' => 'BV', 'country_name' => 'Bouvet Island','id_moneda'=>34]);
		Paises::create(['country_code' => 'BW', 'country_name' => 'Botswana','id_moneda'=>35]);
		Paises::create(['country_code' => 'BY', 'country_name' => 'Belarus','id_moneda'=>36]);
		Paises::create(['country_code' => 'BZ', 'country_name' => 'Belize','id_moneda'=>37]);
		Paises::create(['country_code' => 'CA', 'country_name' => 'Canada','id_moneda'=>38]);
		Paises::create(['country_code' => 'CC', 'country_name' => 'Cocos Islands','id_moneda'=>39]);
		Paises::create(['country_code' => 'CD', 'country_name' => 'Democratic Republic of the Congo','id_moneda'=>40]);
		Paises::create(['country_code' => 'CF', 'country_name' => 'Central African Republic','id_moneda'=>41]);
		Paises::create(['country_code' => 'CG', 'country_name' => 'Republic of the Congo','id_moneda'=>42]);
		Paises::create(['country_code' => 'CH', 'country_name' => 'Switzerland','id_moneda'=>43]);
		Paises::create(['country_code' => 'CI', 'country_name' => 'Ivory Coast','id_moneda'=>44]);
		Paises::create(['country_code' => 'CK', 'country_name' => 'Cook Islands','id_moneda'=>45]);
		Paises::create(['country_code' => 'CL', 'country_name' => 'Chile','id_moneda'=>46]);
		Paises::create(['country_code' => 'CM', 'country_name' => 'Cameroon','id_moneda'=>47]);
		Paises::create(['country_code' => 'CN', 'country_name' => 'China','id_moneda'=>48]);
		Paises::create(['country_code' => 'CO', 'country_name' => 'Colombia','id_moneda'=>49]);
		Paises::create(['country_code' => 'CR', 'country_name' => 'Costa Rica','id_moneda'=>50]);
		Paises::create(['country_code' => 'CS', 'country_name' => 'Serbia and Montenegro','id_moneda'=>1]);
		Paises::create(['country_code' => 'CU', 'country_name' => 'Cuba','id_moneda'=>51]);
		Paises::create(['country_code' => 'CV', 'country_name' => 'Cape Verde','id_moneda'=>52]);
		Paises::create(['country_code' => 'CW', 'country_name' => 'Curaçao','id_moneda'=>53]);
		Paises::create(['country_code' => 'CX', 'country_name' => 'Christmas Island','id_moneda'=>54]);
		Paises::create(['country_code' => 'CY', 'country_name' => 'Cyprus','id_moneda'=>55]);
		Paises::create(['country_code' => 'CZ', 'country_name' => 'Czech Republic','id_moneda'=>56]);
		Paises::create(['country_code' => 'DE', 'country_name' => 'Germany','id_moneda'=>57]);
		Paises::create(['country_code' => 'DJ', 'country_name' => 'Djibouti','id_moneda'=>58]);
		Paises::create(['country_code' => 'DK', 'country_name' => 'Denmark','id_moneda'=>59]);
		Paises::create(['country_code' => 'DM', 'country_name' => 'Dominica','id_moneda'=>60]);
		Paises::create(['country_code' => 'DO', 'country_name' => 'Dominican Republic','id_moneda'=>61]);
		Paises::create(['country_code' => 'DZ', 'country_name' => 'Algeria','id_moneda'=>62]);
		Paises::create(['country_code' => 'EC', 'country_name' => 'Ecuador','id_moneda'=>63]);
		Paises::create(['country_code' => 'EE', 'country_name' => 'Estonia','id_moneda'=>64]);
		Paises::create(['country_code' => 'EG', 'country_name' => 'Egypt','id_moneda'=>65]);
		Paises::create(['country_code' => 'EH', 'country_name' => 'Western Sahara','id_moneda'=>66]);
		Paises::create(['country_code' => 'ER', 'country_name' => 'Eritrea','id_moneda'=>67]);
		Paises::create(['country_code' => 'ES', 'country_name' => 'Spain','id_moneda'=>68]);
		Paises::create(['country_code' => 'ET', 'country_name' => 'Ethiopia','id_moneda'=>69]);
		Paises::create(['country_code' => 'FI', 'country_name' => 'Finland','id_moneda'=>70]);
		Paises::create(['country_code' => 'FJ', 'country_name' => 'Fiji','id_moneda'=>71]);
		Paises::create(['country_code' => 'FK', 'country_name' => 'Falkland Islands','id_moneda'=>72]);
		Paises::create(['country_code' => 'FM', 'country_name' => 'Micronesia','id_moneda'=>73]);
		Paises::create(['country_code' => 'FO', 'country_name' => 'Faroe Islands','id_moneda'=>74]);
		Paises::create(['country_code' => 'FR', 'country_name' => 'France','id_moneda'=>75]);
		Paises::create(['country_code' => 'GA', 'country_name' => 'Gabon','id_moneda'=>76]);
		Paises::create(['country_code' => 'GB', 'country_name' => 'United Kingdom','id_moneda'=>77]);
		Paises::create(['country_code' => 'GD', 'country_name' => 'Grenada','id_moneda'=>78]);
		Paises::create(['country_code' => 'GE', 'country_name' => 'Georgia','id_moneda'=>79]);
		Paises::create(['country_code' => 'GF', 'country_name' => 'French Guiana','id_moneda'=>80]);
		Paises::create(['country_code' => 'GG', 'country_name' => 'Guernsey','id_moneda'=>81]);
		Paises::create(['country_code' => 'GH', 'country_name' => 'Ghana','id_moneda'=>82]);
		Paises::create(['country_code' => 'GI', 'country_name' => 'Gibraltar','id_moneda'=>83]);
		Paises::create(['country_code' => 'GL', 'country_name' => 'Greenland','id_moneda'=>84]);
		Paises::create(['country_code' => 'GM', 'country_name' => 'Gambia','id_moneda'=>85]);
		Paises::create(['country_code' => 'GN', 'country_name' => 'Guinea','id_moneda'=>86]);
		Paises::create(['country_code' => 'GP', 'country_name' => 'Guadeloupe','id_moneda'=>87]);
		Paises::create(['country_code' => 'GQ', 'country_name' => 'Equatorial Guinea','id_moneda'=>88]);
		Paises::create(['country_code' => 'GR', 'country_name' => 'Greece','id_moneda'=>89]);
		Paises::create(['country_code' => 'GS', 'country_name' => 'South Georgia and the South Sandwich Islands','id_moneda'=>90]);
		Paises::create(['country_code' => 'GT', 'country_name' => 'Guatemala','id_moneda'=>91]);
		Paises::create(['country_code' => 'GU', 'country_name' => 'Guam','id_moneda'=>92]);
		Paises::create(['country_code' => 'GW', 'country_name' => 'Guinea-Bissau','id_moneda'=>93]);
		Paises::create(['country_code' => 'GY', 'country_name' => 'Guyana','id_moneda'=>94]);
		Paises::create(['country_code' => 'HK', 'country_name' => 'Hong Kong','id_moneda'=>95]);
		Paises::create(['country_code' => 'HM', 'country_name' => 'Heard Island and McDonald Islands','id_moneda'=>96]);
		Paises::create(['country_code' => 'HN', 'country_name' => 'Honduras','id_moneda'=>97]);
		Paises::create(['country_code' => 'HR', 'country_name' => 'Croatia','id_moneda'=>98]);
		Paises::create(['country_code' => 'HT', 'country_name' => 'Haiti','id_moneda'=>99]);
		Paises::create(['country_code' => 'HU', 'country_name' => 'Hungary','id_moneda'=>100]);
		Paises::create(['country_code' => 'ID', 'country_name' => 'Indonesia','id_moneda'=>101]);
		Paises::create(['country_code' => 'IE', 'country_name' => 'Ireland','id_moneda'=>102]);
		Paises::create(['country_code' => 'IL', 'country_name' => 'Israel','id_moneda'=>103]);
		Paises::create(['country_code' => 'IM', 'country_name' => 'Isle of Man','id_moneda'=>104]);
		Paises::create(['country_code' => 'IN', 'country_name' => 'India','id_moneda'=>105]);
		Paises::create(['country_code' => 'IO', 'country_name' => 'British Indian Ocean Territory','id_moneda'=>106]);
		Paises::create(['country_code' => 'IQ', 'country_name' => 'Iraq','id_moneda'=>107]);
		Paises::create(['country_code' => 'IR', 'country_name' => 'Iran','id_moneda'=>108]);
		Paises::create(['country_code' => 'IS', 'country_name' => 'Iceland','id_moneda'=>109]);
		Paises::create(['country_code' => 'IT', 'country_name' => 'Italy','id_moneda'=>110]);
		Paises::create(['country_code' => 'JE', 'country_name' => 'Jersey','id_moneda'=>111]);
		Paises::create(['country_code' => 'JM', 'country_name' => 'Jamaica','id_moneda'=>112]);
		Paises::create(['country_code' => 'JO', 'country_name' => 'Jordan','id_moneda'=>113]);
		Paises::create(['country_code' => 'JP', 'country_name' => 'Japan','id_moneda'=>114]);
		Paises::create(['country_code' => 'KE', 'country_name' => 'Kenya','id_moneda'=>115]);
		Paises::create(['country_code' => 'KG', 'country_name' => 'Kyrgyzstan','id_moneda'=>116]);
		Paises::create(['country_code' => 'KH', 'country_name' => 'Cambodia','id_moneda'=>117]);
		Paises::create(['country_code' => 'KI', 'country_name' => 'Kiribati','id_moneda'=>118]);
		Paises::create(['country_code' => 'KM', 'country_name' => 'Comoros','id_moneda'=>119]);
		Paises::create(['country_code' => 'KN', 'country_name' => 'Saint Kitts and Nevis','id_moneda'=>120]);
		Paises::create(['country_code' => 'KP', 'country_name' => 'North Korea','id_moneda'=>121]);
		Paises::create(['country_code' => 'KR', 'country_name' => 'South Korea','id_moneda'=>122]);
		Paises::create(['country_code' => 'KW', 'country_name' => 'Kuwait','id_moneda'=>123]);
		Paises::create(['country_code' => 'KY', 'country_name' => 'Cayman Islands','id_moneda'=>124]);
		Paises::create(['country_code' => 'KZ', 'country_name' => 'Kazakhstan','id_moneda'=>125]);
		Paises::create(['country_code' => 'LA', 'country_name' => 'Laos','id_moneda'=>126]);
		Paises::create(['country_code' => 'LB', 'country_name' => 'Lebanon','id_moneda'=>127]);
		Paises::create(['country_code' => 'LC', 'country_name' => 'Saint Lucia','id_moneda'=>128]);
		Paises::create(['country_code' => 'LI', 'country_name' => 'Liechtenstein','id_moneda'=>129]);
		Paises::create(['country_code' => 'LK', 'country_name' => 'Sri Lanka','id_moneda'=>130]);
		Paises::create(['country_code' => 'LR', 'country_name' => 'Liberia','id_moneda'=>131]);
		Paises::create(['country_code' => 'LS', 'country_name' => 'Lesotho','id_moneda'=>132]);
		Paises::create(['country_code' => 'LT', 'country_name' => 'Lithuania','id_moneda'=>133]);
		Paises::create(['country_code' => 'LU', 'country_name' => 'Luxembourg','id_moneda'=>134]);
		Paises::create(['country_code' => 'LV', 'country_name' => 'Latvia','id_moneda'=>135]);
		Paises::create(['country_code' => 'LY', 'country_name' => 'Libya','id_moneda'=>136]);
		Paises::create(['country_code' => 'MA', 'country_name' => 'Morocco','id_moneda'=>137]);
		Paises::create(['country_code' => 'MC', 'country_name' => 'Monaco','id_moneda'=>138]);
		Paises::create(['country_code' => 'MD', 'country_name' => 'Moldova','id_moneda'=>139]);
		Paises::create(['country_code' => 'ME', 'country_name' => 'Montenegro','id_moneda'=>140]);
		Paises::create(['country_code' => 'MF', 'country_name' => 'Saint Martin','id_moneda'=>141]);
		Paises::create(['country_code' => 'MG', 'country_name' => 'Madagascar','id_moneda'=>142]);
		Paises::create(['country_code' => 'MH', 'country_name' => 'Marshall Islands','id_moneda'=>143]);
		Paises::create(['country_code' => 'MK', 'country_name' => 'Macedonia','id_moneda'=>144]);
		Paises::create(['country_code' => 'ML', 'country_name' => 'Mali','id_moneda'=>145]);
		Paises::create(['country_code' => 'MM', 'country_name' => 'Myanmar','id_moneda'=>146]);
		Paises::create(['country_code' => 'MN', 'country_name' => 'Mongolia','id_moneda'=>147]);
		Paises::create(['country_code' => 'MO', 'country_name' => 'Macao','id_moneda'=>148]);
		Paises::create(['country_code' => 'MP', 'country_name' => 'Northern Mariana Islands','id_moneda'=>149]);
		Paises::create(['country_code' => 'MQ', 'country_name' => 'Martinique','id_moneda'=>150]);
		Paises::create(['country_code' => 'MR', 'country_name' => 'Mauritania','id_moneda'=>151]);
		Paises::create(['country_code' => 'MS', 'country_name' => 'Montserrat','id_moneda'=>152]);
		Paises::create(['country_code' => 'MT', 'country_name' => 'Malta','id_moneda'=>153]);
		Paises::create(['country_code' => 'MU', 'country_name' => 'Mauritius','id_moneda'=>154]);
		Paises::create(['country_code' => 'MV', 'country_name' => 'Maldives','id_moneda'=>155]);
		Paises::create(['country_code' => 'MW', 'country_name' => 'Malawi','id_moneda'=>156]);
		Paises::create(['country_code' => 'MX', 'country_name' => 'Mexico','id_moneda'=>157]);
		Paises::create(['country_code' => 'MY', 'country_name' => 'Malaysia','id_moneda'=>158]);
		Paises::create(['country_code' => 'MZ', 'country_name' => 'Mozambique','id_moneda'=>159]);
		Paises::create(['country_code' => 'NA', 'country_name' => 'Namibia','id_moneda'=>160]);
		Paises::create(['country_code' => 'NC', 'country_name' => 'New Caledonia','id_moneda'=>161]);
		Paises::create(['country_code' => 'NE', 'country_name' => 'Niger','id_moneda'=>162]);
		Paises::create(['country_code' => 'NF', 'country_name' => 'Norfolk Island','id_moneda'=>163]);
		Paises::create(['country_code' => 'NG', 'country_name' => 'Nigeria','id_moneda'=>164]);
		Paises::create(['country_code' => 'NI', 'country_name' => 'Nicaragua','id_moneda'=>165]);
		Paises::create(['country_code' => 'NL', 'country_name' => 'Netherlands','id_moneda'=>166]);
		Paises::create(['country_code' => 'NO', 'country_name' => 'Norway','id_moneda'=>167]);
		Paises::create(['country_code' => 'NP', 'country_name' => 'Nepal','id_moneda'=>168]);
		Paises::create(['country_code' => 'NR', 'country_name' => 'Nauru','id_moneda'=>169]);
		Paises::create(['country_code' => 'NU', 'country_name' => 'Niue','id_moneda'=>170]);
		Paises::create(['country_code' => 'NZ', 'country_name' => 'New Zealand','id_moneda'=>171]);
		Paises::create(['country_code' => 'OM', 'country_name' => 'Oman','id_moneda'=>172]);
		Paises::create(['country_code' => 'PA', 'country_name' => 'Panama','id_moneda'=>173]);
		Paises::create(['country_code' => 'PE', 'country_name' => 'Peru','id_moneda'=>174]);
		Paises::create(['country_code' => 'PF', 'country_name' => 'French Polynesia','id_moneda'=>175]);
		Paises::create(['country_code' => 'PG', 'country_name' => 'Papua New Guinea','id_moneda'=>176]);
		Paises::create(['country_code' => 'PH', 'country_name' => 'Philippines','id_moneda'=>177]);
		Paises::create(['country_code' => 'PK', 'country_name' => 'Pakistan','id_moneda'=>178]);
		Paises::create(['country_code' => 'PL', 'country_name' => 'Poland','id_moneda'=>179]);
		Paises::create(['country_code' => 'PM', 'country_name' => 'Saint Pierre and Miquelon','id_moneda'=>180]);
		Paises::create(['country_code' => 'PN', 'country_name' => 'Pitcairn','id_moneda'=>181]);
		Paises::create(['country_code' => 'PR', 'country_name' => 'Puerto Rico','id_moneda'=>182]);
		Paises::create(['country_code' => 'PS', 'country_name' => 'Palestinian Territory','id_moneda'=>183]);
		Paises::create(['country_code' => 'PT', 'country_name' => 'Portugal','id_moneda'=>184]);
		Paises::create(['country_code' => 'PW', 'country_name' => 'Palau','id_moneda'=>185]);
		Paises::create(['country_code' => 'PY', 'country_name' => 'Paraguay','id_moneda'=>186]);
		Paises::create(['country_code' => 'QA', 'country_name' => 'Qatar','id_moneda'=>187]);
		Paises::create(['country_code' => 'RE', 'country_name' => 'Reunion','id_moneda'=>188]);
		Paises::create(['country_code' => 'RO', 'country_name' => 'Romania','id_moneda'=>189]);
		Paises::create(['country_code' => 'RS', 'country_name' => 'Serbia','id_moneda'=>190]);
		Paises::create(['country_code' => 'RU', 'country_name' => 'Russia','id_moneda'=>191]);
		Paises::create(['country_code' => 'RW', 'country_name' => 'Rwanda','id_moneda'=>192]);
		Paises::create(['country_code' => 'SA', 'country_name' => 'Saudi Arabia','id_moneda'=>193]);
		Paises::create(['country_code' => 'SB', 'country_name' => 'Solomon Islands','id_moneda'=>194]);
		Paises::create(['country_code' => 'SC', 'country_name' => 'Seychelles','id_moneda'=>195]);
		Paises::create(['country_code' => 'SD', 'country_name' => 'Sudan','id_moneda'=>196]);
		Paises::create(['country_code' => 'SE', 'country_name' => 'Sweden','id_moneda'=>197]);
		Paises::create(['country_code' => 'SG', 'country_name' => 'Singapore','id_moneda'=>198]);
		Paises::create(['country_code' => 'SH', 'country_name' => 'Saint Helena','id_moneda'=>199]);
		Paises::create(['country_code' => 'SI', 'country_name' => 'Slovenia','id_moneda'=>200]);
		Paises::create(['country_code' => 'SJ', 'country_name' => 'Svalbard and Jan Mayen','id_moneda'=>201]);
		Paises::create(['country_code' => 'SK', 'country_name' => 'Slovakia','id_moneda'=>202]);
		Paises::create(['country_code' => 'SL', 'country_name' => 'Sierra Leone','id_moneda'=>203]);
		Paises::create(['country_code' => 'SM', 'country_name' => 'San Marino','id_moneda'=>204]);
		Paises::create(['country_code' => 'SN', 'country_name' => 'Senegal','id_moneda'=>205]);
		Paises::create(['country_code' => 'SO', 'country_name' => 'Somalia','id_moneda'=>206]);
		Paises::create(['country_code' => 'SR', 'country_name' => 'Suriname','id_moneda'=>207]);
		Paises::create(['country_code' => 'SS', 'country_name' => 'South Sudan','id_moneda'=>208]);
		Paises::create(['country_code' => 'ST', 'country_name' => 'Sao Tome and Principe','id_moneda'=>209]);
		Paises::create(['country_code' => 'SV', 'country_name' => 'El Salvador','id_moneda'=>210]);
		Paises::create(['country_code' => 'SX', 'country_name' => 'Sint Maarten','id_moneda'=>211]);
		Paises::create(['country_code' => 'SY', 'country_name' => 'Syria','id_moneda'=>212]);
		Paises::create(['country_code' => 'SZ', 'country_name' => 'Swaziland','id_moneda'=>213]);
		Paises::create(['country_code' => 'TC', 'country_name' => 'Turks and Caicos Islands','id_moneda'=>214]);
		Paises::create(['country_code' => 'TD', 'country_name' => 'Chad','id_moneda'=>215]);
		Paises::create(['country_code' => 'TF', 'country_name' => 'French Southern Territories','id_moneda'=>216]);
		Paises::create(['country_code' => 'TG', 'country_name' => 'Togo','id_moneda'=>217]);
		Paises::create(['country_code' => 'TH', 'country_name' => 'Thailand','id_moneda'=>218]);
		Paises::create(['country_code' => 'TJ', 'country_name' => 'Tajikistan','id_moneda'=>219]);
		Paises::create(['country_code' => 'TK', 'country_name' => 'Tokelau','id_moneda'=>220]);
		Paises::create(['country_code' => 'TL', 'country_name' => 'East Timor','id_moneda'=>221]);
		Paises::create(['country_code' => 'TM', 'country_name' => 'Turkmenistan','id_moneda'=>222]);
		Paises::create(['country_code' => 'TN', 'country_name' => 'Tunisia','id_moneda'=>223]);
		Paises::create(['country_code' => 'TO', 'country_name' => 'Tonga','id_moneda'=>224]);
		Paises::create(['country_code' => 'TR', 'country_name' => 'Turkey','id_moneda'=>225]);
		Paises::create(['country_code' => 'TT', 'country_name' => 'Trinidad and Tobago','id_moneda'=>226]);
		Paises::create(['country_code' => 'TV', 'country_name' => 'Tuvalu','id_moneda'=>227]);
		Paises::create(['country_code' => 'TW', 'country_name' => 'Taiwan','id_moneda'=>228]);
		Paises::create(['country_code' => 'TZ', 'country_name' => 'Tanzania','id_moneda'=>229]);
		Paises::create(['country_code' => 'UA', 'country_name' => 'Ukraine','id_moneda'=>230]);
		Paises::create(['country_code' => 'UG', 'country_name' => 'Uganda','id_moneda'=>231]);
		Paises::create(['country_code' => 'UM', 'country_name' => 'United States Minor Outlying Islands','id_moneda'=>232]);
		Paises::create(['country_code' => 'US', 'country_name' => 'United States','id_moneda'=>233]);
		Paises::create(['country_code' => 'UY', 'country_name' => 'Uruguay','id_moneda'=>234]);
		Paises::create(['country_code' => 'UZ', 'country_name' => 'Uzbekistan','id_moneda'=>235]);
		Paises::create(['country_code' => 'VA', 'country_name' => 'Vatican','id_moneda'=>236]);
		Paises::create(['country_code' => 'VC', 'country_name' => 'Saint Vincent and the Grenadines','id_moneda'=>237]);
		Paises::create(['country_code' => 'VE', 'country_name' => 'Venezuela','id_moneda'=>238]);
		Paises::create(['country_code' => 'VG', 'country_name' => 'British Virgin Islands','id_moneda'=>239]);
		Paises::create(['country_code' => 'VI', 'country_name' => 'U.S. Virgin Islands','id_moneda'=>240]);
		Paises::create(['country_code' => 'VN', 'country_name' => 'Vietnam','id_moneda'=>241]);
		Paises::create(['country_code' => 'VU', 'country_name' => 'Vanuatu','id_moneda'=>242]);
		Paises::create(['country_code' => 'WF', 'country_name' => 'Wallis and Futuna','id_moneda'=>243]);
		Paises::create(['country_code' => 'WS', 'country_name' => 'Samoa','id_moneda'=>244]);
		Paises::create(['country_code' => 'XK', 'country_name' => 'Kosovo','id_moneda'=>245]);
		Paises::create(['country_code' => 'YE', 'country_name' => 'Yemen','id_moneda'=>246]);
		Paises::create(['country_code' => 'YT', 'country_name' => 'Mayotte','id_moneda'=>247]);
		Paises::create(['country_code' => 'ZA', 'country_name' => 'South Africa','id_moneda'=>248]);
		Paises::create(['country_code' => 'ZM', 'country_name' => 'Zambia','id_moneda'=>249]);
		Paises::create(['country_code' => 'ZW', 'country_name' => 'Zimbabwe','id_moneda'=>250]);
	}

}
