<?php

use App\Models\Catalogo\ZonaHoraria;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class ZonaHorariaSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
        Model::unguard();
        DB::table('catalogo_zona_horaria')->truncate();

        ZonaHoraria::create(['id_pais'=>1,'zona_horaria'=>'Europe/Andorra','zona_vanidad'=>'Andorra']);
		ZonaHoraria::create(['id_pais'=>2,'zona_horaria'=>'Asia/Dubai','zona_vanidad'=>'Dubai']);
		ZonaHoraria::create(['id_pais'=>3,'zona_horaria'=>'Asia/Kabul','zona_vanidad'=>'Kabul']);
		ZonaHoraria::create(['id_pais'=>4,'zona_horaria'=>'America/Antigua','zona_vanidad'=>'Antigua']);
		ZonaHoraria::create(['id_pais'=>5,'zona_horaria'=>'America/Anguilla','zona_vanidad'=>'Anguilla']);
		ZonaHoraria::create(['id_pais'=>6,'zona_horaria'=>'Europe/Tirane','zona_vanidad'=>'Tirane']);
		ZonaHoraria::create(['id_pais'=>7,'zona_horaria'=>'Asia/Yerevan','zona_vanidad'=>'Yerevan']);
		ZonaHoraria::create(['id_pais'=>9,'zona_horaria'=>'Africa/Luanda','zona_vanidad'=>'Luanda']);
		ZonaHoraria::create(['id_pais'=>10,'zona_horaria'=>'Antarctica/McMurdo','zona_vanidad'=>'McMurdo']);
		ZonaHoraria::create(['id_pais'=>10,'zona_horaria'=>'Antarctica/Rothera','zona_vanidad'=>'Rothera']);
		ZonaHoraria::create(['id_pais'=>10,'zona_horaria'=>'Antarctica/Palmer','zona_vanidad'=>'Palmer']);
		ZonaHoraria::create(['id_pais'=>10,'zona_horaria'=>'Antarctica/Mawson','zona_vanidad'=>'Mawson']);
		ZonaHoraria::create(['id_pais'=>10,'zona_horaria'=>'Antarctica/Davis','zona_vanidad'=>'Davis']);
		ZonaHoraria::create(['id_pais'=>10,'zona_horaria'=>'Antarctica/Casey','zona_vanidad'=>'Casey']);
		ZonaHoraria::create(['id_pais'=>10,'zona_horaria'=>'Antarctica/Vostok','zona_vanidad'=>'Vostok']);
		ZonaHoraria::create(['id_pais'=>10,'zona_horaria'=>'Antarctica/DumontDUrville','zona_vanidad'=>'DumontDUrville']);
		ZonaHoraria::create(['id_pais'=>10,'zona_horaria'=>'Antarctica/Syowa','zona_vanidad'=>'Syowa']);
		ZonaHoraria::create(['id_pais'=>10,'zona_horaria'=>'Antarctica/Troll','zona_vanidad'=>'Troll']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/Buenos_Aires','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/Cordoba','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/Salta','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/Jujuy','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/Tucuman','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/Catamarca','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/La_Rioja','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/San_Juan','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/Mendoza','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/San_Luis','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/Rio_Gallegos','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>11,'zona_horaria'=>'America/Argentina/Ushuaia','zona_vanidad'=>'Argentina']);
		ZonaHoraria::create(['id_pais'=>12,'zona_horaria'=>'Pacific/Pago_Pago','zona_vanidad'=>'Pago Pago']);
		ZonaHoraria::create(['id_pais'=>13,'zona_horaria'=>'Europe/Vienna','zona_vanidad'=>'Vienna']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Lord_Howe','zona_vanidad'=>'Lord Howe']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Antarctica/Macquarie','zona_vanidad'=>'Macquarie']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Hobart','zona_vanidad'=>'Hobart']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Currie','zona_vanidad'=>'Currie']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Melbourne','zona_vanidad'=>'Melbourne']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Sydney','zona_vanidad'=>'Sydney']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Broken_Hill','zona_vanidad'=>'Broken Hill']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Brisbane','zona_vanidad'=>'Brisbane']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Lindeman','zona_vanidad'=>'Lindeman']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Adelaide','zona_vanidad'=>'Adelaide']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Darwin','zona_vanidad'=>'Darwin']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Perth','zona_vanidad'=>'Perth']);
		ZonaHoraria::create(['id_pais'=>14,'zona_horaria'=>'Australia/Eucla','zona_vanidad'=>'Eucla']);
		ZonaHoraria::create(['id_pais'=>15,'zona_horaria'=>'America/Aruba','zona_vanidad'=>'Aruba']);
		ZonaHoraria::create(['id_pais'=>16,'zona_horaria'=>'Europe/Mariehamn','zona_vanidad'=>'Mariehamn']);
		ZonaHoraria::create(['id_pais'=>17,'zona_horaria'=>'Asia/Baku','zona_vanidad'=>'Baku']);
		ZonaHoraria::create(['id_pais'=>18,'zona_horaria'=>'Europe/Sarajevo','zona_vanidad'=>'Sarajevo']);
		ZonaHoraria::create(['id_pais'=>19,'zona_horaria'=>'America/Barbados','zona_vanidad'=>'Barbados']);
		ZonaHoraria::create(['id_pais'=>20,'zona_horaria'=>'Asia/Dhaka','zona_vanidad'=>'Dhaka']);
		ZonaHoraria::create(['id_pais'=>21,'zona_horaria'=>'Europe/Brussels','zona_vanidad'=>'Brussels']);
		ZonaHoraria::create(['id_pais'=>22,'zona_horaria'=>'Africa/Ouagadougou','zona_vanidad'=>'Ouagadougou']);
		ZonaHoraria::create(['id_pais'=>23,'zona_horaria'=>'Europe/Sofia','zona_vanidad'=>'Sofia']);
		ZonaHoraria::create(['id_pais'=>24,'zona_horaria'=>'Asia/Bahrain','zona_vanidad'=>'Bahrain']);
		ZonaHoraria::create(['id_pais'=>25,'zona_horaria'=>'Africa/Bujumbura','zona_vanidad'=>'Bujumbura']);
		ZonaHoraria::create(['id_pais'=>26,'zona_horaria'=>'Africa/Porto-Novo','zona_vanidad'=>'Porto-Novo']);
		ZonaHoraria::create(['id_pais'=>27,'zona_horaria'=>'America/St_Barthelemy','zona_vanidad'=>'St Barthelemy']);
		ZonaHoraria::create(['id_pais'=>28,'zona_horaria'=>'Atlantic/Bermuda','zona_vanidad'=>'Bermuda']);
		ZonaHoraria::create(['id_pais'=>29,'zona_horaria'=>'Asia/Brunei','zona_vanidad'=>'Brunei']);
		ZonaHoraria::create(['id_pais'=>30,'zona_horaria'=>'America/La_Paz','zona_vanidad'=>'La Paz']);
		ZonaHoraria::create(['id_pais'=>31,'zona_horaria'=>'America/Kralendijk','zona_vanidad'=>'Kralendijk']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Noronha','zona_vanidad'=>'Noronha']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Belem','zona_vanidad'=>'Belem']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Fortaleza','zona_vanidad'=>'Fortaleza']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Recife','zona_vanidad'=>'Recife']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Araguaina','zona_vanidad'=>'Araguaina']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Maceio','zona_vanidad'=>'Maceio']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Bahia','zona_vanidad'=>'Bahia']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Sao_Paulo','zona_vanidad'=>'Sao Paulo']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Campo_Grande','zona_vanidad'=>'Campo Grande']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Cuiaba','zona_vanidad'=>'Cuiaba']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Santarem','zona_vanidad'=>'Santarem']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Porto_Velho','zona_vanidad'=>'Porto Velho']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Boa_Vista','zona_vanidad'=>'Boa Vista']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Manaus','zona_vanidad'=>'Manaus']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Eirunepe','zona_vanidad'=>'Eirunepe']);
		ZonaHoraria::create(['id_pais'=>32,'zona_horaria'=>'America/Rio_Branco','zona_vanidad'=>'Rio Branco']);
		ZonaHoraria::create(['id_pais'=>33,'zona_horaria'=>'America/Nassau','zona_vanidad'=>'Nassau']);
		ZonaHoraria::create(['id_pais'=>34,'zona_horaria'=>'Asia/Thimphu','zona_vanidad'=>'Thimphu']);
		ZonaHoraria::create(['id_pais'=>36,'zona_horaria'=>'Africa/Gaborone','zona_vanidad'=>'Gaborone']);
		ZonaHoraria::create(['id_pais'=>37,'zona_horaria'=>'Europe/Minsk','zona_vanidad'=>'Minsk']);
		ZonaHoraria::create(['id_pais'=>38,'zona_horaria'=>'America/Belize','zona_vanidad'=>'Belize']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/St_Johns','zona_vanidad'=>'St Johns']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Halifax','zona_vanidad'=>'Halifax']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Glace_Bay','zona_vanidad'=>'Glace Bay']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Moncton','zona_vanidad'=>'Moncton']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Goose_Bay','zona_vanidad'=>'Goose Bay']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Blanc-Sablon','zona_vanidad'=>'Blanc-Sablon']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Toronto','zona_vanidad'=>'Toronto']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Nipigon','zona_vanidad'=>'Nipigon']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Thunder_Bay','zona_vanidad'=>'Thunder Bay']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Iqaluit','zona_vanidad'=>'Iqaluit']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Pangnirtung','zona_vanidad'=>'Pangnirtung']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Resolute','zona_vanidad'=>'Resolute']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Atikokan','zona_vanidad'=>'Atikokan']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Rankin_Inlet','zona_vanidad'=>'Rankin Inlet']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Winnipeg','zona_vanidad'=>'Winnipeg']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Rainy_River','zona_vanidad'=>'Rainy River']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Regina','zona_vanidad'=>'Regina']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Swift_Current','zona_vanidad'=>'Swift Current']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Edmonton','zona_vanidad'=>'Edmonton']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Cambridge_Bay','zona_vanidad'=>'Cambridge Bay']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Yellowknife','zona_vanidad'=>'Yellowknife']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Inuvik','zona_vanidad'=>'Inuvik']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Creston','zona_vanidad'=>'Creston']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Dawson_Creek','zona_vanidad'=>'Dawson Creek']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Vancouver','zona_vanidad'=>'Vancouver']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Whitehorse','zona_vanidad'=>'Whitehorse']);
		ZonaHoraria::create(['id_pais'=>39,'zona_horaria'=>'America/Dawson','zona_vanidad'=>'Dawson']);
		ZonaHoraria::create(['id_pais'=>40,'zona_horaria'=>'Indian/Cocos','zona_vanidad'=>'Cocos']);
		ZonaHoraria::create(['id_pais'=>41,'zona_horaria'=>'Africa/Kinshasa','zona_vanidad'=>'Kinshasa']);
		ZonaHoraria::create(['id_pais'=>41,'zona_horaria'=>'Africa/Lubumbashi','zona_vanidad'=>'Lubumbashi']);
		ZonaHoraria::create(['id_pais'=>42,'zona_horaria'=>'Africa/Bangui','zona_vanidad'=>'Bangui']);
		ZonaHoraria::create(['id_pais'=>43,'zona_horaria'=>'Africa/Brazzaville','zona_vanidad'=>'Brazzaville']);
		ZonaHoraria::create(['id_pais'=>44,'zona_horaria'=>'Europe/Zurich','zona_vanidad'=>'Zurich']);
		ZonaHoraria::create(['id_pais'=>45,'zona_horaria'=>'Africa/Abidjan','zona_vanidad'=>'Abidjan']);
		ZonaHoraria::create(['id_pais'=>46,'zona_horaria'=>'Pacific/Rarotonga','zona_vanidad'=>'Rarotonga']);
		ZonaHoraria::create(['id_pais'=>47,'zona_horaria'=>'America/Santiago','zona_vanidad'=>'Santiago']);
		ZonaHoraria::create(['id_pais'=>47,'zona_horaria'=>'Pacific/Easter','zona_vanidad'=>'Easter']);
		ZonaHoraria::create(['id_pais'=>48,'zona_horaria'=>'Africa/Douala','zona_vanidad'=>'Douala']);
		ZonaHoraria::create(['id_pais'=>49,'zona_horaria'=>'Asia/Shanghai','zona_vanidad'=>'Shanghai']);
		ZonaHoraria::create(['id_pais'=>49,'zona_horaria'=>'Asia/Urumqi','zona_vanidad'=>'Urumqi']);
		ZonaHoraria::create(['id_pais'=>50,'zona_horaria'=>'America/Bogota','zona_vanidad'=>'Bogota']);
		ZonaHoraria::create(['id_pais'=>51,'zona_horaria'=>'America/Costa_Rica','zona_vanidad'=>'Costa Rica']);
		ZonaHoraria::create(['id_pais'=>53,'zona_horaria'=>'America/Havana','zona_vanidad'=>'Havana']);
		ZonaHoraria::create(['id_pais'=>54,'zona_horaria'=>'Atlantic/Cape_Verde','zona_vanidad'=>'Cape Verde']);
		ZonaHoraria::create(['id_pais'=>55,'zona_horaria'=>'America/Curacao','zona_vanidad'=>'Curacao']);
		ZonaHoraria::create(['id_pais'=>56,'zona_horaria'=>'Indian/Christmas','zona_vanidad'=>'Christmas']);
		ZonaHoraria::create(['id_pais'=>57,'zona_horaria'=>'Asia/Nicosia','zona_vanidad'=>'Nicosia']);
		ZonaHoraria::create(['id_pais'=>58,'zona_horaria'=>'Europe/Prague','zona_vanidad'=>'Prague']);
		ZonaHoraria::create(['id_pais'=>59,'zona_horaria'=>'Europe/Berlin','zona_vanidad'=>'Berlin']);
		ZonaHoraria::create(['id_pais'=>59,'zona_horaria'=>'Europe/Busingen','zona_vanidad'=>'Busingen']);
		ZonaHoraria::create(['id_pais'=>60,'zona_horaria'=>'Africa/Djibouti','zona_vanidad'=>'Djibouti']);
		ZonaHoraria::create(['id_pais'=>61,'zona_horaria'=>'Europe/Copenhagen','zona_vanidad'=>'Copenhagen']);
		ZonaHoraria::create(['id_pais'=>62,'zona_horaria'=>'America/Dominica','zona_vanidad'=>'Dominica']);
		ZonaHoraria::create(['id_pais'=>63,'zona_horaria'=>'America/Santo_Domingo','zona_vanidad'=>'Santo Domingo']);
		ZonaHoraria::create(['id_pais'=>64,'zona_horaria'=>'Africa/Algiers','zona_vanidad'=>'Algiers']);
		ZonaHoraria::create(['id_pais'=>65,'zona_horaria'=>'America/Guayaquil','zona_vanidad'=>'Guayaquil']);
		ZonaHoraria::create(['id_pais'=>65,'zona_horaria'=>'Pacific/Galapagos','zona_vanidad'=>'Galapagos']);
		ZonaHoraria::create(['id_pais'=>66,'zona_horaria'=>'Europe/Tallinn','zona_vanidad'=>'Tallinn']);
		ZonaHoraria::create(['id_pais'=>67,'zona_horaria'=>'Africa/Cairo','zona_vanidad'=>'Cairo']);
		ZonaHoraria::create(['id_pais'=>68,'zona_horaria'=>'Africa/El_Aaiun','zona_vanidad'=>'El Aaiun']);
		ZonaHoraria::create(['id_pais'=>69,'zona_horaria'=>'Africa/Asmara','zona_vanidad'=>'Asmara']);
		ZonaHoraria::create(['id_pais'=>70,'zona_horaria'=>'Europe/Madrid','zona_vanidad'=>'Madrid']);
		ZonaHoraria::create(['id_pais'=>70,'zona_horaria'=>'Africa/Ceuta','zona_vanidad'=>'Ceuta']);
		ZonaHoraria::create(['id_pais'=>70,'zona_horaria'=>'Atlantic/Canary','zona_vanidad'=>'Canary']);
		ZonaHoraria::create(['id_pais'=>71,'zona_horaria'=>'Africa/Addis_Ababa','zona_vanidad'=>'Addis Ababa']);
		ZonaHoraria::create(['id_pais'=>72,'zona_horaria'=>'Europe/Helsinki','zona_vanidad'=>'Helsinki']);
		ZonaHoraria::create(['id_pais'=>73,'zona_horaria'=>'Pacific/Fiji','zona_vanidad'=>'Fiji']);
		ZonaHoraria::create(['id_pais'=>74,'zona_horaria'=>'Atlantic/Stanley','zona_vanidad'=>'Stanley']);
		ZonaHoraria::create(['id_pais'=>75,'zona_horaria'=>'Pacific/Chuuk','zona_vanidad'=>'Chuuk']);
		ZonaHoraria::create(['id_pais'=>75,'zona_horaria'=>'Pacific/Pohnpei','zona_vanidad'=>'Pohnpei']);
		ZonaHoraria::create(['id_pais'=>75,'zona_horaria'=>'Pacific/Kosrae','zona_vanidad'=>'Kosrae']);
		ZonaHoraria::create(['id_pais'=>76,'zona_horaria'=>'Atlantic/Faroe','zona_vanidad'=>'Faroe']);
		ZonaHoraria::create(['id_pais'=>77,'zona_horaria'=>'Europe/Paris','zona_vanidad'=>'Paris']);
		ZonaHoraria::create(['id_pais'=>78,'zona_horaria'=>'Africa/Libreville','zona_vanidad'=>'Libreville']);
		ZonaHoraria::create(['id_pais'=>79,'zona_horaria'=>'Europe/London','zona_vanidad'=>'London']);
		ZonaHoraria::create(['id_pais'=>80,'zona_horaria'=>'America/Grenada','zona_vanidad'=>'Grenada']);
		ZonaHoraria::create(['id_pais'=>81,'zona_horaria'=>'Asia/Tbilisi','zona_vanidad'=>'Tbilisi']);
		ZonaHoraria::create(['id_pais'=>82,'zona_horaria'=>'America/Cayenne','zona_vanidad'=>'Cayenne']);
		ZonaHoraria::create(['id_pais'=>83,'zona_horaria'=>'Europe/Guernsey','zona_vanidad'=>'Guernsey']);
		ZonaHoraria::create(['id_pais'=>84,'zona_horaria'=>'Africa/Accra','zona_vanidad'=>'Accra']);
		ZonaHoraria::create(['id_pais'=>85,'zona_horaria'=>'Europe/Gibraltar','zona_vanidad'=>'Gibraltar']);
		ZonaHoraria::create(['id_pais'=>86,'zona_horaria'=>'America/Godthab','zona_vanidad'=>'Godthab']);
		ZonaHoraria::create(['id_pais'=>86,'zona_horaria'=>'America/Danmarkshavn','zona_vanidad'=>'Danmarkshavn']);
		ZonaHoraria::create(['id_pais'=>86,'zona_horaria'=>'America/Scoresbysund','zona_vanidad'=>'Scoresbysund']);
		ZonaHoraria::create(['id_pais'=>86,'zona_horaria'=>'America/Thule','zona_vanidad'=>'Thule']);
		ZonaHoraria::create(['id_pais'=>87,'zona_horaria'=>'Africa/Banjul','zona_vanidad'=>'Banjul']);
		ZonaHoraria::create(['id_pais'=>88,'zona_horaria'=>'Africa/Conakry','zona_vanidad'=>'Conakry']);
		ZonaHoraria::create(['id_pais'=>89,'zona_horaria'=>'America/Guadeloupe','zona_vanidad'=>'Guadeloupe']);
		ZonaHoraria::create(['id_pais'=>90,'zona_horaria'=>'Africa/Malabo','zona_vanidad'=>'Malabo']);
		ZonaHoraria::create(['id_pais'=>91,'zona_horaria'=>'Europe/Athens','zona_vanidad'=>'Athens']);
		ZonaHoraria::create(['id_pais'=>92,'zona_horaria'=>'Atlantic/South_Georgia','zona_vanidad'=>'South Georgia']);
		ZonaHoraria::create(['id_pais'=>93,'zona_horaria'=>'America/Guatemala','zona_vanidad'=>'Guatemala']);
		ZonaHoraria::create(['id_pais'=>94,'zona_horaria'=>'Pacific/Guam','zona_vanidad'=>'Guam']);
		ZonaHoraria::create(['id_pais'=>95,'zona_horaria'=>'Africa/Bissau','zona_vanidad'=>'Bissau']);
		ZonaHoraria::create(['id_pais'=>96,'zona_horaria'=>'America/Guyana','zona_vanidad'=>'Guyana']);
		ZonaHoraria::create(['id_pais'=>97,'zona_horaria'=>'Asia/Hong_Kong','zona_vanidad'=>'Hong Kong']);
		ZonaHoraria::create(['id_pais'=>99,'zona_horaria'=>'America/Tegucigalpa','zona_vanidad'=>'Tegucigalpa']);
		ZonaHoraria::create(['id_pais'=>100,'zona_horaria'=>'Europe/Zagreb','zona_vanidad'=>'Zagreb']);
		ZonaHoraria::create(['id_pais'=>101,'zona_horaria'=>'America/Port-au-Prince','zona_vanidad'=>'Port-au-Prince']);
		ZonaHoraria::create(['id_pais'=>102,'zona_horaria'=>'Europe/Budapest','zona_vanidad'=>'Budapest']);
		ZonaHoraria::create(['id_pais'=>103,'zona_horaria'=>'Asia/Jakarta','zona_vanidad'=>'Jakarta']);
		ZonaHoraria::create(['id_pais'=>103,'zona_horaria'=>'Asia/Pontianak','zona_vanidad'=>'Pontianak']);
		ZonaHoraria::create(['id_pais'=>103,'zona_horaria'=>'Asia/Makassar','zona_vanidad'=>'Makassar']);
		ZonaHoraria::create(['id_pais'=>103,'zona_horaria'=>'Asia/Jayapura','zona_vanidad'=>'Jayapura']);
		ZonaHoraria::create(['id_pais'=>104,'zona_horaria'=>'Europe/Dublin','zona_vanidad'=>'Dublin']);
		ZonaHoraria::create(['id_pais'=>105,'zona_horaria'=>'Asia/Jerusalem','zona_vanidad'=>'Jerusalem']);
		ZonaHoraria::create(['id_pais'=>106,'zona_horaria'=>'Europe/Isle_of_Man','zona_vanidad'=>'Isle of Man']);
		ZonaHoraria::create(['id_pais'=>107,'zona_horaria'=>'Asia/Kolkata','zona_vanidad'=>'Kolkata']);
		ZonaHoraria::create(['id_pais'=>108,'zona_horaria'=>'Indian/Chagos','zona_vanidad'=>'Chagos']);
		ZonaHoraria::create(['id_pais'=>109,'zona_horaria'=>'Asia/Baghdad','zona_vanidad'=>'Baghdad']);
		ZonaHoraria::create(['id_pais'=>110,'zona_horaria'=>'Asia/Tehran','zona_vanidad'=>'Tehran']);
		ZonaHoraria::create(['id_pais'=>111,'zona_horaria'=>'Atlantic/Reykjavik','zona_vanidad'=>'Reykjavik']);
		ZonaHoraria::create(['id_pais'=>112,'zona_horaria'=>'Europe/Rome','zona_vanidad'=>'Rome']);
		ZonaHoraria::create(['id_pais'=>113,'zona_horaria'=>'Europe/Jersey','zona_vanidad'=>'Jersey']);
		ZonaHoraria::create(['id_pais'=>114,'zona_horaria'=>'America/Jamaica','zona_vanidad'=>'Jamaica']);
		ZonaHoraria::create(['id_pais'=>115,'zona_horaria'=>'Asia/Amman','zona_vanidad'=>'Amman']);
		ZonaHoraria::create(['id_pais'=>116,'zona_horaria'=>'Asia/Tokyo','zona_vanidad'=>'Tokyo']);
		ZonaHoraria::create(['id_pais'=>117,'zona_horaria'=>'Africa/Nairobi','zona_vanidad'=>'Nairobi']);
		ZonaHoraria::create(['id_pais'=>118,'zona_horaria'=>'Asia/Bishkek','zona_vanidad'=>'Bishkek']);
		ZonaHoraria::create(['id_pais'=>119,'zona_horaria'=>'Asia/Phnom_Penh','zona_vanidad'=>'Phnom Penh']);
		ZonaHoraria::create(['id_pais'=>120,'zona_horaria'=>'Pacific/Tarawa','zona_vanidad'=>'Tarawa']);
		ZonaHoraria::create(['id_pais'=>120,'zona_horaria'=>'Pacific/Enderbury','zona_vanidad'=>'Enderbury']);
		ZonaHoraria::create(['id_pais'=>120,'zona_horaria'=>'Pacific/Kiritimati','zona_vanidad'=>'Kiritimati']);
		ZonaHoraria::create(['id_pais'=>121,'zona_horaria'=>'Indian/Comoro','zona_vanidad'=>'Comoro']);
		ZonaHoraria::create(['id_pais'=>122,'zona_horaria'=>'America/St_Kitts','zona_vanidad'=>'St Kitts']);
		ZonaHoraria::create(['id_pais'=>123,'zona_horaria'=>'Asia/Pyongyang','zona_vanidad'=>'Pyongyang']);
		ZonaHoraria::create(['id_pais'=>124,'zona_horaria'=>'Asia/Seoul','zona_vanidad'=>'Seoul']);
		ZonaHoraria::create(['id_pais'=>125,'zona_horaria'=>'Asia/Kuwait','zona_vanidad'=>'Kuwait']);
		ZonaHoraria::create(['id_pais'=>126,'zona_horaria'=>'America/Cayman','zona_vanidad'=>'Cayman']);
		ZonaHoraria::create(['id_pais'=>127,'zona_horaria'=>'Asia/Almaty','zona_vanidad'=>'Almaty']);
		ZonaHoraria::create(['id_pais'=>127,'zona_horaria'=>'Asia/Qyzylorda','zona_vanidad'=>'Qyzylorda']);
		ZonaHoraria::create(['id_pais'=>127,'zona_horaria'=>'Asia/Aqtobe','zona_vanidad'=>'Aqtobe']);
		ZonaHoraria::create(['id_pais'=>127,'zona_horaria'=>'Asia/Aqtau','zona_vanidad'=>'Aqtau']);
		ZonaHoraria::create(['id_pais'=>127,'zona_horaria'=>'Asia/Oral','zona_vanidad'=>'Oral']);
		ZonaHoraria::create(['id_pais'=>128,'zona_horaria'=>'Asia/Vientiane','zona_vanidad'=>'Vientiane']);
		ZonaHoraria::create(['id_pais'=>129,'zona_horaria'=>'Asia/Beirut','zona_vanidad'=>'Beirut']);
		ZonaHoraria::create(['id_pais'=>130,'zona_horaria'=>'America/St_Lucia','zona_vanidad'=>'St Lucia']);
		ZonaHoraria::create(['id_pais'=>131,'zona_horaria'=>'Europe/Vaduz','zona_vanidad'=>'Vaduz']);
		ZonaHoraria::create(['id_pais'=>132,'zona_horaria'=>'Asia/Colombo','zona_vanidad'=>'Colombo']);
		ZonaHoraria::create(['id_pais'=>133,'zona_horaria'=>'Africa/Monrovia','zona_vanidad'=>'Monrovia']);
		ZonaHoraria::create(['id_pais'=>134,'zona_horaria'=>'Africa/Maseru','zona_vanidad'=>'Maseru']);
		ZonaHoraria::create(['id_pais'=>135,'zona_horaria'=>'Europe/Vilnius','zona_vanidad'=>'Vilnius']);
		ZonaHoraria::create(['id_pais'=>136,'zona_horaria'=>'Europe/Luxembourg','zona_vanidad'=>'Luxembourg']);
		ZonaHoraria::create(['id_pais'=>137,'zona_horaria'=>'Europe/Riga','zona_vanidad'=>'Riga']);
		ZonaHoraria::create(['id_pais'=>138,'zona_horaria'=>'Africa/Tripoli','zona_vanidad'=>'Tripoli']);
		ZonaHoraria::create(['id_pais'=>139,'zona_horaria'=>'Africa/Casablanca','zona_vanidad'=>'Casablanca']);
		ZonaHoraria::create(['id_pais'=>140,'zona_horaria'=>'Europe/Monaco','zona_vanidad'=>'Monaco']);
		ZonaHoraria::create(['id_pais'=>141,'zona_horaria'=>'Europe/Chisinau','zona_vanidad'=>'Chisinau']);
		ZonaHoraria::create(['id_pais'=>142,'zona_horaria'=>'Europe/Podgorica','zona_vanidad'=>'Podgorica']);
		ZonaHoraria::create(['id_pais'=>143,'zona_horaria'=>'America/Marigot','zona_vanidad'=>'Marigot']);
		ZonaHoraria::create(['id_pais'=>144,'zona_horaria'=>'Indian/Antananarivo','zona_vanidad'=>'Antananarivo']);
		ZonaHoraria::create(['id_pais'=>145,'zona_horaria'=>'Pacific/Majuro','zona_vanidad'=>'Majuro']);
		ZonaHoraria::create(['id_pais'=>145,'zona_horaria'=>'Pacific/Kwajalein','zona_vanidad'=>'Kwajalein']);
		ZonaHoraria::create(['id_pais'=>146,'zona_horaria'=>'Europe/Skopje','zona_vanidad'=>'Skopje']);
		ZonaHoraria::create(['id_pais'=>147,'zona_horaria'=>'Africa/Bamako','zona_vanidad'=>'Bamako']);
		ZonaHoraria::create(['id_pais'=>148,'zona_horaria'=>'Asia/Rangoon','zona_vanidad'=>'Rangoon']);
		ZonaHoraria::create(['id_pais'=>149,'zona_horaria'=>'Asia/Ulaanbaatar','zona_vanidad'=>'Ulaanbaatar']);
		ZonaHoraria::create(['id_pais'=>149,'zona_horaria'=>'Asia/Hovd','zona_vanidad'=>'Hovd']);
		ZonaHoraria::create(['id_pais'=>149,'zona_horaria'=>'Asia/Choibalsan','zona_vanidad'=>'Choibalsan']);
		ZonaHoraria::create(['id_pais'=>150,'zona_horaria'=>'Asia/Macau','zona_vanidad'=>'Macau']);
		ZonaHoraria::create(['id_pais'=>151,'zona_horaria'=>'Pacific/Saipan','zona_vanidad'=>'Saipan']);
		ZonaHoraria::create(['id_pais'=>152,'zona_horaria'=>'America/Martinique','zona_vanidad'=>'Martinique']);
		ZonaHoraria::create(['id_pais'=>153,'zona_horaria'=>'Africa/Nouakchott','zona_vanidad'=>'Nouakchott']);
		ZonaHoraria::create(['id_pais'=>154,'zona_horaria'=>'America/Montserrat','zona_vanidad'=>'Montserrat']);
		ZonaHoraria::create(['id_pais'=>155,'zona_horaria'=>'Europe/Malta','zona_vanidad'=>'Malta']);
		ZonaHoraria::create(['id_pais'=>156,'zona_horaria'=>'Indian/Mauritius','zona_vanidad'=>'Mauritius']);
		ZonaHoraria::create(['id_pais'=>157,'zona_horaria'=>'Indian/Maldives','zona_vanidad'=>'Maldives']);
		ZonaHoraria::create(['id_pais'=>158,'zona_horaria'=>'Africa/Blantyre','zona_vanidad'=>'Blantyre']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Mexico_City','zona_vanidad'=>'Mexico City']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Cancun','zona_vanidad'=>'Cancun']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Merida','zona_vanidad'=>'Merida']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Monterrey','zona_vanidad'=>'Monterrey']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Matamoros','zona_vanidad'=>'Matamoros']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Mazatlan','zona_vanidad'=>'Mazatlan']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Chihuahua','zona_vanidad'=>'Chihuahua']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Ojinaga','zona_vanidad'=>'Ojinaga']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Hermosillo','zona_vanidad'=>'Hermosillo']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Tijuana','zona_vanidad'=>'Tijuana']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Santa_Isabel','zona_vanidad'=>'Santa Isabel']);
		ZonaHoraria::create(['id_pais'=>159,'zona_horaria'=>'America/Bahia_Banderas','zona_vanidad'=>'Bahia Banderas']);
		ZonaHoraria::create(['id_pais'=>160,'zona_horaria'=>'Asia/Kuala_Lumpur','zona_vanidad'=>'Kuala Lumpur']);
		ZonaHoraria::create(['id_pais'=>160,'zona_horaria'=>'Asia/Kuching','zona_vanidad'=>'Kuching']);
		ZonaHoraria::create(['id_pais'=>161,'zona_horaria'=>'Africa/Maputo','zona_vanidad'=>'Maputo']);
		ZonaHoraria::create(['id_pais'=>162,'zona_horaria'=>'Africa/Windhoek','zona_vanidad'=>'Windhoek']);
		ZonaHoraria::create(['id_pais'=>163,'zona_horaria'=>'Pacific/Noumea','zona_vanidad'=>'Noumea']);
		ZonaHoraria::create(['id_pais'=>164,'zona_horaria'=>'Africa/Niamey','zona_vanidad'=>'Niamey']);
		ZonaHoraria::create(['id_pais'=>165,'zona_horaria'=>'Pacific/Norfolk','zona_vanidad'=>'Norfolk']);
		ZonaHoraria::create(['id_pais'=>166,'zona_horaria'=>'Africa/Lagos','zona_vanidad'=>'Lagos']);
		ZonaHoraria::create(['id_pais'=>167,'zona_horaria'=>'America/Managua','zona_vanidad'=>'Managua']);
		ZonaHoraria::create(['id_pais'=>168,'zona_horaria'=>'Europe/Amsterdam','zona_vanidad'=>'Amsterdam']);
		ZonaHoraria::create(['id_pais'=>169,'zona_horaria'=>'Europe/Oslo','zona_vanidad'=>'Oslo']);
		ZonaHoraria::create(['id_pais'=>170,'zona_horaria'=>'Asia/Kathmandu','zona_vanidad'=>'Kathmandu']);
		ZonaHoraria::create(['id_pais'=>171,'zona_horaria'=>'Pacific/Nauru','zona_vanidad'=>'Nauru']);
		ZonaHoraria::create(['id_pais'=>172,'zona_horaria'=>'Pacific/Niue','zona_vanidad'=>'Niue']);
		ZonaHoraria::create(['id_pais'=>173,'zona_horaria'=>'Pacific/Auckland','zona_vanidad'=>'Auckland']);
		ZonaHoraria::create(['id_pais'=>173,'zona_horaria'=>'Pacific/Chatham','zona_vanidad'=>'Chatham']);
		ZonaHoraria::create(['id_pais'=>174,'zona_horaria'=>'Asia/Muscat','zona_vanidad'=>'Muscat']);
		ZonaHoraria::create(['id_pais'=>175,'zona_horaria'=>'America/Panama','zona_vanidad'=>'Panama']);
		ZonaHoraria::create(['id_pais'=>176,'zona_horaria'=>'America/Lima','zona_vanidad'=>'Lima']);
		ZonaHoraria::create(['id_pais'=>177,'zona_horaria'=>'Pacific/Tahiti','zona_vanidad'=>'Tahiti']);
		ZonaHoraria::create(['id_pais'=>177,'zona_horaria'=>'Pacific/Marquesas','zona_vanidad'=>'Marquesas']);
		ZonaHoraria::create(['id_pais'=>177,'zona_horaria'=>'Pacific/Gambier','zona_vanidad'=>'Gambier']);
		ZonaHoraria::create(['id_pais'=>178,'zona_horaria'=>'Pacific/Port_Moresby','zona_vanidad'=>'Port Moresby']);
		ZonaHoraria::create(['id_pais'=>178,'zona_horaria'=>'Pacific/Bougainville','zona_vanidad'=>'Bougainville']);
		ZonaHoraria::create(['id_pais'=>179,'zona_horaria'=>'Asia/Manila','zona_vanidad'=>'Manila']);
		ZonaHoraria::create(['id_pais'=>180,'zona_horaria'=>'Asia/Karachi','zona_vanidad'=>'Karachi']);
		ZonaHoraria::create(['id_pais'=>181,'zona_horaria'=>'Europe/Warsaw','zona_vanidad'=>'Warsaw']);
		ZonaHoraria::create(['id_pais'=>182,'zona_horaria'=>'America/Miquelon','zona_vanidad'=>'Miquelon']);
		ZonaHoraria::create(['id_pais'=>183,'zona_horaria'=>'Pacific/Pitcairn','zona_vanidad'=>'Pitcairn']);
		ZonaHoraria::create(['id_pais'=>184,'zona_horaria'=>'America/Puerto_Rico','zona_vanidad'=>'Puerto Rico']);
		ZonaHoraria::create(['id_pais'=>185,'zona_horaria'=>'Asia/Gaza','zona_vanidad'=>'Gaza']);
		ZonaHoraria::create(['id_pais'=>185,'zona_horaria'=>'Asia/Hebron','zona_vanidad'=>'Hebron']);
		ZonaHoraria::create(['id_pais'=>186,'zona_horaria'=>'Europe/Lisbon','zona_vanidad'=>'Lisbon']);
		ZonaHoraria::create(['id_pais'=>186,'zona_horaria'=>'Atlantic/Madeira','zona_vanidad'=>'Madeira']);
		ZonaHoraria::create(['id_pais'=>186,'zona_horaria'=>'Atlantic/Azores','zona_vanidad'=>'Azores']);
		ZonaHoraria::create(['id_pais'=>187,'zona_horaria'=>'Pacific/Palau','zona_vanidad'=>'Palau']);
		ZonaHoraria::create(['id_pais'=>188,'zona_horaria'=>'America/Asuncion','zona_vanidad'=>'Asuncion']);
		ZonaHoraria::create(['id_pais'=>189,'zona_horaria'=>'Asia/Qatar','zona_vanidad'=>'Qatar']);
		ZonaHoraria::create(['id_pais'=>190,'zona_horaria'=>'Indian/Reunion','zona_vanidad'=>'Reunion']);
		ZonaHoraria::create(['id_pais'=>191,'zona_horaria'=>'Europe/Bucharest','zona_vanidad'=>'Bucharest']);
		ZonaHoraria::create(['id_pais'=>192,'zona_horaria'=>'Europe/Belgrade','zona_vanidad'=>'Belgrade']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Europe/Kaliningrad','zona_vanidad'=>'Kaliningrad']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Europe/Moscow','zona_vanidad'=>'Moscow']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Europe/Simferopol','zona_vanidad'=>'Simferopol']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Europe/Volgograd','zona_vanidad'=>'Volgograd']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Europe/Samara','zona_vanidad'=>'Samara']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Yekaterinburg','zona_vanidad'=>'Yekaterinburg']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Omsk','zona_vanidad'=>'Omsk']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Novosibirsk','zona_vanidad'=>'Novosibirsk']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Novokuznetsk','zona_vanidad'=>'Novokuznetsk']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Krasnoyarsk','zona_vanidad'=>'Krasnoyarsk']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Irkutsk','zona_vanidad'=>'Irkutsk']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Chita','zona_vanidad'=>'Chita']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Yakutsk','zona_vanidad'=>'Yakutsk']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Khandyga','zona_vanidad'=>'Khandyga']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Vladivostok','zona_vanidad'=>'Vladivostok']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Sakhalin','zona_vanidad'=>'Sakhalin']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Ust-Nera','zona_vanidad'=>'Ust-Nera']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Magadan','zona_vanidad'=>'Magadan']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Srednekolymsk','zona_vanidad'=>'Srednekolymsk']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Kamchatka','zona_vanidad'=>'Kamchatka']);
		ZonaHoraria::create(['id_pais'=>193,'zona_horaria'=>'Asia/Anadyr','zona_vanidad'=>'Anadyr']);
		ZonaHoraria::create(['id_pais'=>194,'zona_horaria'=>'Africa/Kigali','zona_vanidad'=>'Kigali']);
		ZonaHoraria::create(['id_pais'=>195,'zona_horaria'=>'Asia/Riyadh','zona_vanidad'=>'Riyadh']);
		ZonaHoraria::create(['id_pais'=>196,'zona_horaria'=>'Pacific/Guadalcanal','zona_vanidad'=>'Guadalcanal']);
		ZonaHoraria::create(['id_pais'=>197,'zona_horaria'=>'Indian/Mahe','zona_vanidad'=>'Mahe']);
		ZonaHoraria::create(['id_pais'=>198,'zona_horaria'=>'Africa/Khartoum','zona_vanidad'=>'Khartoum']);
		ZonaHoraria::create(['id_pais'=>199,'zona_horaria'=>'Europe/Stockholm','zona_vanidad'=>'Stockholm']);
		ZonaHoraria::create(['id_pais'=>200,'zona_horaria'=>'Asia/Singapore','zona_vanidad'=>'Singapore']);
		ZonaHoraria::create(['id_pais'=>201,'zona_horaria'=>'Atlantic/St_Helena','zona_vanidad'=>'St Helena']);
		ZonaHoraria::create(['id_pais'=>202,'zona_horaria'=>'Europe/Ljubljana','zona_vanidad'=>'Ljubljana']);
		ZonaHoraria::create(['id_pais'=>203,'zona_horaria'=>'Arctic/Longyearbyen','zona_vanidad'=>'Longyearbyen']);
		ZonaHoraria::create(['id_pais'=>204,'zona_horaria'=>'Europe/Bratislava','zona_vanidad'=>'Bratislava']);
		ZonaHoraria::create(['id_pais'=>205,'zona_horaria'=>'Africa/Freetown','zona_vanidad'=>'Freetown']);
		ZonaHoraria::create(['id_pais'=>206,'zona_horaria'=>'Europe/San_Marino','zona_vanidad'=>'San Marino']);
		ZonaHoraria::create(['id_pais'=>207,'zona_horaria'=>'Africa/Dakar','zona_vanidad'=>'Dakar']);
		ZonaHoraria::create(['id_pais'=>208,'zona_horaria'=>'Africa/Mogadishu','zona_vanidad'=>'Mogadishu']);
		ZonaHoraria::create(['id_pais'=>209,'zona_horaria'=>'America/Paramaribo','zona_vanidad'=>'Paramaribo']);
		ZonaHoraria::create(['id_pais'=>210,'zona_horaria'=>'Africa/Juba','zona_vanidad'=>'Juba']);
		ZonaHoraria::create(['id_pais'=>211,'zona_horaria'=>'Africa/Sao_Tome','zona_vanidad'=>'Sao Tome']);
		ZonaHoraria::create(['id_pais'=>212,'zona_horaria'=>'America/El_Salvador','zona_vanidad'=>'El Salvador']);
		ZonaHoraria::create(['id_pais'=>213,'zona_horaria'=>'America/Lower_Princes','zona_vanidad'=>'Lower Princes']);
		ZonaHoraria::create(['id_pais'=>214,'zona_horaria'=>'Asia/Damascus','zona_vanidad'=>'Damascus']);
		ZonaHoraria::create(['id_pais'=>215,'zona_horaria'=>'Africa/Mbabane','zona_vanidad'=>'Mbabane']);
		ZonaHoraria::create(['id_pais'=>216,'zona_horaria'=>'America/Grand_Turk','zona_vanidad'=>'Grand Turk']);
		ZonaHoraria::create(['id_pais'=>217,'zona_horaria'=>'Africa/Ndjamena','zona_vanidad'=>'Ndjamena']);
		ZonaHoraria::create(['id_pais'=>218,'zona_horaria'=>'Indian/Kerguelen','zona_vanidad'=>'Kerguelen']);
		ZonaHoraria::create(['id_pais'=>219,'zona_horaria'=>'Africa/Lome','zona_vanidad'=>'Lome']);
		ZonaHoraria::create(['id_pais'=>220,'zona_horaria'=>'Asia/Bangkok','zona_vanidad'=>'Bangkok']);
		ZonaHoraria::create(['id_pais'=>221,'zona_horaria'=>'Asia/Dushanbe','zona_vanidad'=>'Dushanbe']);
		ZonaHoraria::create(['id_pais'=>222,'zona_horaria'=>'Pacific/Fakaofo','zona_vanidad'=>'Fakaofo']);
		ZonaHoraria::create(['id_pais'=>223,'zona_horaria'=>'Asia/Dili','zona_vanidad'=>'Dili']);
		ZonaHoraria::create(['id_pais'=>224,'zona_horaria'=>'Asia/Ashgabat','zona_vanidad'=>'Ashgabat']);
		ZonaHoraria::create(['id_pais'=>225,'zona_horaria'=>'Africa/Tunis','zona_vanidad'=>'Tunis']);
		ZonaHoraria::create(['id_pais'=>226,'zona_horaria'=>'Pacific/Tongatapu','zona_vanidad'=>'Tongatapu']);
		ZonaHoraria::create(['id_pais'=>227,'zona_horaria'=>'Europe/Istanbul','zona_vanidad'=>'Istanbul']);
		ZonaHoraria::create(['id_pais'=>228,'zona_horaria'=>'America/Port_of_Spain','zona_vanidad'=>'Port of Spain']);
		ZonaHoraria::create(['id_pais'=>229,'zona_horaria'=>'Pacific/Funafuti','zona_vanidad'=>'Funafuti']);
		ZonaHoraria::create(['id_pais'=>230,'zona_horaria'=>'Asia/Taipei','zona_vanidad'=>'Taipei']);
		ZonaHoraria::create(['id_pais'=>231,'zona_horaria'=>'Africa/Dar_es_Salaam','zona_vanidad'=>'Dar es Salaam']);
		ZonaHoraria::create(['id_pais'=>232,'zona_horaria'=>'Europe/Kiev','zona_vanidad'=>'Kiev']);
		ZonaHoraria::create(['id_pais'=>232,'zona_horaria'=>'Europe/Uzhgorod','zona_vanidad'=>'Uzhgorod']);
		ZonaHoraria::create(['id_pais'=>232,'zona_horaria'=>'Europe/Zaporozhye','zona_vanidad'=>'Zaporozhye']);
		ZonaHoraria::create(['id_pais'=>233,'zona_horaria'=>'Africa/Kampala','zona_vanidad'=>'Kampala']);
		ZonaHoraria::create(['id_pais'=>234,'zona_horaria'=>'Pacific/Johnston','zona_vanidad'=>'Johnston']);
		ZonaHoraria::create(['id_pais'=>234,'zona_horaria'=>'Pacific/Midway','zona_vanidad'=>'Midway']);
		ZonaHoraria::create(['id_pais'=>234,'zona_horaria'=>'Pacific/Wake','zona_vanidad'=>'Wake']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/New_York','zona_vanidad'=>'New York']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Detroit','zona_vanidad'=>'Detroit']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Kentucky/Louisville','zona_vanidad'=>'Kentucky']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Kentucky/Monticello','zona_vanidad'=>'Kentucky']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Indiana/Indianapolis','zona_vanidad'=>'Indiana']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Indiana/Vincennes','zona_vanidad'=>'Indiana']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Indiana/Winamac','zona_vanidad'=>'Indiana']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Indiana/Marengo','zona_vanidad'=>'Indiana']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Indiana/Petersburg','zona_vanidad'=>'Indiana']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Indiana/Vevay','zona_vanidad'=>'Indiana']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Chicago','zona_vanidad'=>'Chicago']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Indiana/Tell_City','zona_vanidad'=>'Indiana']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Indiana/Knox','zona_vanidad'=>'Indiana']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Menominee','zona_vanidad'=>'Menominee']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/North_Dakota/Center','zona_vanidad'=>'North Dakota']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/North_Dakota/New_Salem','zona_vanidad'=>'North Dakota']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/North_Dakota/Beulah','zona_vanidad'=>'North Dakota']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Denver','zona_vanidad'=>'Denver']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Boise','zona_vanidad'=>'Boise']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Phoenix','zona_vanidad'=>'Phoenix']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Los_Angeles','zona_vanidad'=>'Los Angeles']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Metlakatla','zona_vanidad'=>'Metlakatla']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Anchorage','zona_vanidad'=>'Anchorage']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Juneau','zona_vanidad'=>'Juneau']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Sitka','zona_vanidad'=>'Sitka']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Yakutat','zona_vanidad'=>'Yakutat']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Nome','zona_vanidad'=>'Nome']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'America/Adak','zona_vanidad'=>'Adak']);
		ZonaHoraria::create(['id_pais'=>235,'zona_horaria'=>'Pacific/Honolulu','zona_vanidad'=>'Honolulu']);
		ZonaHoraria::create(['id_pais'=>236,'zona_horaria'=>'America/Montevideo','zona_vanidad'=>'Montevideo']);
		ZonaHoraria::create(['id_pais'=>237,'zona_horaria'=>'Asia/Samarkand','zona_vanidad'=>'Samarkand']);
		ZonaHoraria::create(['id_pais'=>237,'zona_horaria'=>'Asia/Tashkent','zona_vanidad'=>'Tashkent']);
		ZonaHoraria::create(['id_pais'=>238,'zona_horaria'=>'Europe/Vatican','zona_vanidad'=>'Vatican']);
		ZonaHoraria::create(['id_pais'=>239,'zona_horaria'=>'America/St_Vincent','zona_vanidad'=>'St Vincent']);
		ZonaHoraria::create(['id_pais'=>240,'zona_horaria'=>'America/Caracas','zona_vanidad'=>'Caracas']);
		ZonaHoraria::create(['id_pais'=>241,'zona_horaria'=>'America/Tortola','zona_vanidad'=>'Tortola']);
		ZonaHoraria::create(['id_pais'=>242,'zona_horaria'=>'America/St_Thomas','zona_vanidad'=>'St Thomas']);
		ZonaHoraria::create(['id_pais'=>243,'zona_horaria'=>'Asia/Ho_Chi_Minh','zona_vanidad'=>'Ho Chi Minh']);
		ZonaHoraria::create(['id_pais'=>244,'zona_horaria'=>'Pacific/Efate','zona_vanidad'=>'Efate']);
		ZonaHoraria::create(['id_pais'=>245,'zona_horaria'=>'Pacific/Wallis','zona_vanidad'=>'Wallis']);
		ZonaHoraria::create(['id_pais'=>246,'zona_horaria'=>'Pacific/Apia','zona_vanidad'=>'Apia']);
		ZonaHoraria::create(['id_pais'=>248,'zona_horaria'=>'Asia/Aden','zona_vanidad'=>'Aden']);
		ZonaHoraria::create(['id_pais'=>249,'zona_horaria'=>'Indian/Mayotte','zona_vanidad'=>'Mayotte']);
		ZonaHoraria::create(['id_pais'=>250,'zona_horaria'=>'Africa/Johannesburg','zona_vanidad'=>'Johannesburg']);
		ZonaHoraria::create(['id_pais'=>251,'zona_horaria'=>'Africa/Lusaka','zona_vanidad'=>'Lusaka']);
		ZonaHoraria::create(['id_pais'=>252,'zona_horaria'=>'Africa/Harare','zona_vanidad'=>'Harare']);
	}

}
